TRUNCATE TABLE SJ_FACTURACION_PPP_DIARIA 

GO

INSERT INTO SJ_FACTURACION_PPP_DIARIA SELECT * FROM SJ_FACTURACION_PPP





TRUNCATE TABLE SJ_FACTURACION_PPP_CANAL_DIARIA 

GO

INSERT INTO SJ_FACTURACION_PPP_CANAL_DIARIA SELECT * FROM SJ_FACTURACION_PPP_CANAL